version: "3.7"
services:
 db:
   image: postgres:14
   env_file:
     - .env
   environment:
     POSTGRES_DB: ${DB_NAME}
     POSTGRES_USER: ${DB_USER}
     POSTGRES_PASSWORD: ${DB_PASS}
   ports:
     - "5433:5432"
   volumes:
     - /home/ubuntu/db_data:/var/lib/postgresql/data
     - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
     - ./sql/fill.sql:/docker-entrypoint-initdb.d/fill.sql

volumes:
 postgresdb-data:
   driver: local
